repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: black
        name: Run black
        stages: [commit]
        language: system
        entry: black --check --diff
        types: [python]

      - id: flake8
        name: Run flake8
        stages: [commit]
        language: system
        entry: flake8 
        types: [python]
        verbose: true

      - id: isort-config
        name: Run isort
        stages: [commit]
        language: system
        entry: isort --show-config
        types: [python]
        verbose: true

      - id: isort-diff
        name: Run isort
        stages: [commit]
        language: system
        entry: isort --check --diff
        types: [python]
        verbose: true

      - id: isort-version
        name: Run isort
        stages: [commit]
        language: system
        entry: isort --version
        types: [python]
        verbose: true